# Generated by Django 5.1.3 on 2024-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyemail',
            old_name='title',
            new_name='subject',
        ),
    ]
