# Generated by Django 5.1.3 on 2024-12-10 14:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_title_dailyemail_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('acumbamail_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Mail List',
                'verbose_name_plural': 'Mail Lists',
                'db_table': 'mail_list',
            },
        ),
        migrations.AddField(
            model_name='dailyemail',
            name='mail_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.maillist'),
        ),
    ]
