# Generated by Django 5.1.3 on 2024-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_maillist_subscribers_historicalmaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaillist',
            name='bounced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmaillist',
            name='unsubscribed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maillist',
            name='bounced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maillist',
            name='unsubscribed',
            field=models.IntegerField(default=0),
        ),
    ]
