# Generated by Django 5.1.3 on 2024-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_historicalmaillist_bounced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaillist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maillist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
