# Generated by Django 5.1.3 on 2024-12-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_historicalmaillist_active_maillist_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemail',
            name='mail_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_emails', to='campaigns.maillist'),
        ),
    ]
