# Generated by Django 5.1.3 on 2024-12-11 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_dailyemail_mail_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maillist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='mail_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
