# Generated by Django 5.1.3 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_alter_sells_product_alter_sells_student'),
        ('campaigns', '0009_maillist_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='mail_lists', to='academy.student'),
        ),
    ]
