# Generated by Django 5.1.4 on 2024-12-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_dailyemail_acumbamail_id_dailyemail_total_bounces_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyEmail',
            new_name='EmailCampaigns',
        ),
    ]
