# Generated by Django 5.1.4 on 2024-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_rename_dailyemail_emailcampaigns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaigns',
            options={'verbose_name': 'Email Campaign', 'verbose_name_plural': 'Email Campaigns'},
        ),
        migrations.AlterModelTable(
            name='emailcampaigns',
            table='email_campaign',
        ),
    ]
