# Generated by Django 5.1.4 on 2024-12-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_emailcampaigns_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigns',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el email ha sido enviado.'),
        ),
        migrations.AddField(
            model_name='emailcampaigns',
            name='send_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que se ha enviado el email.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaigns',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en la que se programó el envío del email.', null=True),
        ),
    ]
