# Generated by Django 5.1.4 on 2024-12-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_emailcampaigns_is_sent_emailcampaigns_send_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigns',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el email es un borrador.'),
        ),
    ]
