# Generated by Django 5.1.4 on 2024-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_historicallead_lead'),
        ('campaigns', '0015_emailcampaigns_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillist',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='mail_lists', to='academy.lead'),
        ),
    ]
