# Generated by Django 5.1.4 on 2024-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_maillist_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaigns',
            name='scheduled_at',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha y hora en la que se programó el envío del email.', null=True),
        ),
    ]
