# Generated by Django 5.1.4 on 2024-12-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_emailcampaigns_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigns',
            name='preferred_day',
            field=models.CharField(choices=[('any', 'Cualquier día'), ('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='any', help_text='Día preferido para enviar el email.', max_length=10),
        ),
    ]
