# Generated by Django 5.1.3 on 2024-11-20 14:53

import academy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_id', models.BigIntegerField(null=True, unique=True)),
                ('ezy_id', models.IntegerField(unique=True)),
                ('product_type', models.CharField(choices=[(academy.models.ProductTypes['COURSE'], 'course'), (academy.models.ProductTypes['BUNDLE_COURSE'], 'bundle_course'), (academy.models.ProductTypes['PRIVATE_CHAT'], 'private_chat'), (academy.models.ProductTypes['COMMUNITY'], 'community'), (academy.models.ProductTypes['GROUP'], 'group'), (academy.models.ProductTypes['DIGITAL_PRODUCT'], 'digital_product'), (academy.models.ProductTypes['PHYSICAL_PRODUCT'], 'physical_product'), (academy.models.ProductTypes['VIDEO_LIBRARY'], 'video_library'), (academy.models.ProductTypes['MEMBERSHIP'], 'membership'), (academy.models.ProductTypes['ORGANIZATION'], 'organization')], max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('tags', models.JSONField(default=list, null=True)),
                ('zoho_tags', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_id', models.BigIntegerField(null=True, unique=True)),
                ('zoho_is_lead', models.BooleanField(default=True)),
                ('ezy_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=800, unique=True)),
                ('tags', models.JSONField(default=list, null=True)),
                ('zoho_tags', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, null=True)),
                ('zoho_id', models.BigIntegerField(null=True)),
                ('gateway', models.CharField(max_length=100)),
                ('sell_price', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
                'db_table': 'sells',
                'unique_together': {('student', 'product', 'zoho_id')},
            },
        ),
    ]
