# Generated by Django 5.1.3 on 2024-11-21 09:16

import academy.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('zoho_id', models.BigIntegerField(db_index=True, null=True)),
                ('ezy_id', models.IntegerField(db_index=True)),
                ('product_type', models.CharField(choices=[(academy.models.ProductTypes['COURSE'], 'course'), (academy.models.ProductTypes['BUNDLE_COURSE'], 'bundle_course'), (academy.models.ProductTypes['PRIVATE_CHAT'], 'private_chat'), (academy.models.ProductTypes['COMMUNITY'], 'community'), (academy.models.ProductTypes['GROUP'], 'group'), (academy.models.ProductTypes['DIGITAL_PRODUCT'], 'digital_product'), (academy.models.ProductTypes['PHYSICAL_PRODUCT'], 'physical_product'), (academy.models.ProductTypes['VIDEO_LIBRARY'], 'video_library'), (academy.models.ProductTypes['MEMBERSHIP'], 'membership'), (academy.models.ProductTypes['ORGANIZATION'], 'organization')], max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('tags', models.JSONField(default=list, null=True)),
                ('zoho_tags', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSells',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, null=True)),
                ('zoho_id', models.BigIntegerField(null=True)),
                ('gateway', models.CharField(max_length=100)),
                ('sell_price', models.FloatField(default=0)),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academy.product')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academy.student')),
            ],
            options={
                'verbose_name': 'historical Sell',
                'verbose_name_plural': 'historical Sells',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('zoho_id', models.BigIntegerField(db_index=True, null=True)),
                ('zoho_is_lead', models.BooleanField(default=True)),
                ('ezy_id', models.IntegerField(db_index=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=800)),
                ('tags', models.JSONField(default=list, null=True)),
                ('zoho_tags', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Student',
                'verbose_name_plural': 'historical Students',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
