# Generated by Django 5.1.3 on 2024-11-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_historicalproduct_historicalsells_historicalstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0)),
                ('current_chapter', models.CharField(max_length=300, null=True)),
                ('current_lesson', models.CharField(max_length=300, null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('started_date', models.DateTimeField(null=True)),
                ('last_visit', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Courses Progress',
                'db_table': 'course_progress',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
