# Generated by Django 5.1.3 on 2024-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='zoho_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
