# Generated by Django 5.1.3 on 2024-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_historicalproduct_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('color', models.CharField(default='blue', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products_tags', to='academy.tag'),
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='students_tags', to='academy.tag'),
        ),
    ]
