# Generated by Django 5.1.3 on 2024-11-25 15:48

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_tag_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization')], default=academy.models.ProductTypes['COURSE'], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization')], default=academy.models.ProductTypes['COURSE'], max_length=50),
        ),
    ]
