# Generated by Django 5.1.3 on 2024-11-25 15:53

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_historicalproduct_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], default=academy.models.CourseStatus['PUBLISHED'], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], default=academy.models.CourseStatus['PUBLISHED'], max_length=50, null=True),
        ),
    ]
