# Generated by Django 5.1.3 on 2024-11-26 09:10

import academy.models
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_historicalproduct_status_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='zoho_tags',
        ),
        migrations.RemoveField(
            model_name='historicalsells',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='zoho_is_lead',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='zoho_tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zoho_tags',
        ),
        migrations.AlterUniqueTogether(
            name='sells',
            unique_together={('student', 'product')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='zoho_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='zoho_is_lead',
        ),
        migrations.RemoveField(
            model_name='student',
            name='zoho_tags',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='historicalsells',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='historicalsells',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='sells',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sells',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='student',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_date',
            field=models.DateTimeField(help_text='Date when the course was completed', null=True),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='last_visit',
            field=models.DateTimeField(help_text='Last visit to the course', null=True),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='started_date',
            field=models.DateTimeField(help_text='Date when the course was started', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization'), ('EVENT', 'event')], default=academy.models.ProductTypes['COURSE'], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsells',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date when the product was sold'),
        ),
        migrations.AlterField(
            model_name='historicalsells',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL')], default=academy.models.PaymentGateway['STRIPE'], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization'), ('EVENT', 'event')], default=academy.models.ProductTypes['COURSE'], max_length=50),
        ),
        migrations.AlterField(
            model_name='sells',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the product was sold'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL')], default=academy.models.PaymentGateway['STRIPE'], max_length=100),
        ),
        migrations.RemoveField(
            model_name='sells',
            name='zoho_id',
        ),
    ]
