# Generated by Django 5.1.3 on 2024-11-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_courseprogress_zoho_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='academy.product'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='academy.student'),
        ),
    ]
