# Generated by Django 5.1.3 on 2024-12-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_alter_sells_product_alter_sells_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student Paid',
                'verbose_name_plural': 'Students Paid',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.student',),
        ),
        migrations.CreateModel(
            name='StudentLeadProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student Lead',
                'verbose_name_plural': 'Students Lead',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.student',),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='academy_tags',
        ),
    ]
