# Generated by Django 5.1.3 on 2024-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_delete_studentcontactproxy_delete_studentleadproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='engagement_score',
            field=models.FloatField(default=20, help_text='Peso adicional para el score del estudiante al comprar este producto.'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='community_score',
            field=models.FloatField(default=0, help_text='Score basado en participación en comunidad.'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='email_engagement_score',
            field=models.FloatField(default=0, help_text='Score basado en interacción con correos (apertura y clics).'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='engagement_score',
            field=models.FloatField(default=0, help_text='Score general de actividad y participación.'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='purchase_score',
            field=models.FloatField(default=0, help_text='Score basado en compras realizadas.'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='retention_score',
            field=models.FloatField(default=0, help_text='Score basado en retención y visitas repetidas.'),
        ),
        migrations.AddField(
            model_name='product',
            name='engagement_score',
            field=models.FloatField(default=20, help_text='Peso adicional para el score del estudiante al comprar este producto.'),
        ),
        migrations.AddField(
            model_name='student',
            name='community_score',
            field=models.FloatField(default=0, help_text='Score basado en participación en comunidad.'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_engagement_score',
            field=models.FloatField(default=0, help_text='Score basado en interacción con correos (apertura y clics).'),
        ),
        migrations.AddField(
            model_name='student',
            name='engagement_score',
            field=models.FloatField(default=0, help_text='Score general de actividad y participación.'),
        ),
        migrations.AddField(
            model_name='student',
            name='purchase_score',
            field=models.FloatField(default=0, help_text='Score basado en compras realizadas.'),
        ),
        migrations.AddField(
            model_name='student',
            name='retention_score',
            field=models.FloatField(default=0, help_text='Score basado en retención y visitas repetidas.'),
        ),
    ]
