# Generated by Django 5.1.4 on 2024-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_historicalstudent_total_score_student_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization'), ('EVENT', 'event')], default='course', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('COURSE', 'course'), ('BUNDLE_COURSE', 'bundle_course'), ('PRIVATE_CHAT', 'private_chat'), ('COMMUNITY', 'community'), ('GROUP', 'group'), ('DIGITAL_PRODUCT', 'digital_product'), ('PHYSICAL_PRODUCT', 'physical_product'), ('VIDEO_LIBRARY', 'video_library'), ('MEMBERSHIP', 'membership'), ('ORGANIZATION', 'organization'), ('EVENT', 'event')], default='course', max_length=50),
        ),
    ]
