alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: URL_TOKEN
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:gYdK8fBQZLAjDSlS44MytRJW7+WO+RO9:bKmPTWMXuIw7uE36tK6FO3aSw+gicToBO/XKFHAdoldnWNShqWS0Vid2bd41qCr9WxmRTJa2j5xhS74GYvSnLDpMhuVJkUU0sO91b2XbfI4D]
- key: NOTION_TOKEN
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:PLBQE/U4jDUyQoPZefYQUX1Vt97Xzep8:tlQfbxpEQnZiHteS+wNugv1EXtJInA6WZ0wCOBEXNGgUr2d9rhWdEWDR6vebSFr8Z6gjcdUxxBHHTZS6DOUB8mx0]
- key: NOTION_DATABASE_ID
  scope: RUN_AND_BUILD_TIME
  value: 12e9eddc9f9c8067abaddc798615c212
- key: ANTHROPIC_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:fNUM9zos27OaMve/d1BjP6rRvMFzY4N6:4L5aOT1Mt5+ncXSXsl/i1RJZnNKy/asZPY6a86aLR7gXbKkFl1FlI9AwR52B8BBO5zra1AnVrw9Le01sMQ5r6jLdqfc02gUzpgpbXMkvtb12xPi73kRmAmlGY0yjTbJwCsY1DiTa7r15XBduRcwWsX2dfcVem1hBx6HTig==]
- key: SUMMARY_MIN_WORDS
  scope: RUN_AND_BUILD_TIME
  value: "100"
- key: SUMMARY_MAX_WORDS
  scope: RUN_AND_BUILD_TIME
  value: "250"
- key: FORCE_PROCESS_FEEDS
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: LLM_ENGINE
  scope: RUN_AND_BUILD_TIME
  value: anthropic
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: rediss://default:AVNS_oy6Z29RjDMvreskP1ES@redis-main-do-user-16996249-0.c.db.ondigitalocean.com:25061?ssl_cert_reqs=CERT_OPTIONA
- key: PUSHOVER_USER
  scope: RUN_AND_BUILD_TIME
  value: umcz6c3a2tomh7ndxdoq8ici2nk6ar
- key: PUSHOVER_TOKEN
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:5Qy/igGDLJ8jw0QqWgOzbP5a8YvHHzAt:7GpP3gQYy10UiGu1xQGRMix3SUO4HTRR3x22UpuqpnOq1uEg/KEGw1Q0uS3Dnw==]
- key: SENTRY_DSN
  scope: RUN_AND_BUILD_TIME
  value: https://2df2b4289b9a8859542df43da5276431@o4508245270134784.ingest.de.sentry.io/4508245273542736
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: webhooks
    match:
      path:
        prefix: /
name: alice-bob-news
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: the-alice-and-bob/news-feed
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: webhooks
  run_command: /entrypoint-web
  source_dir: /
workers:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: the-alice-and-bob/news-feed
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: news-feed2
  run_command: /entrypoint-celery-worker
  source_dir: /
