services:

  webhooks:
    image: alicebob:latest
    env_file:
      - .compose_env
    environment:
      - URL_TOKEN=${URL_TOKEN}
      - FORCE_PROCESS_FEEDS=true
      - REDIS_URL=redis://redis:6379/1
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "8000:8080"
    entrypoint: "/entrypoint-web"
    networks:
      - redis-net

  workers:
    image: alicebob:latest
    env_file:
      - .compose_env
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SUMMARY_MIN_WORDS=100
      - SUMMARY_MAX_WORDS=150
      - LLM_ENGINE=anthropic
      - REDIS_URL=redis://redis:6379/1
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - SENTRY_DSN=${SENTRY_DSN}
    entrypoint: "/entrypoint-celery-worker"
    networks:
      - redis-net
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6400:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - redis-net

networks:
  redis-net:

volumes:
    vault-file:
    minio_data:
