services:

  webhooks:
    image: ghcr.io/the-alice-and-bob/alicebob:latest
    environment:
      - URL_TOKEN=${URL_TOKEN}
      - FORCE_PROCESS_FEEDS=true
      - CELERY_BROKER_URL=amqps://xphtxctu:v5DL_TOb3a42b0ji4eklkhiYuCg_lOwv@kebnekaise.lmq.cloudamqp.com/xphtxctu
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "80:8080"
    entrypoint: "/entrypoint-web"
    networks:
      - rabbitmq-net

  workers:
    image: ghcr.io/the-alice-and-bob/alicebob:latest
    environment:
      - URL_TOKEN=${URL_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SUMMARY_MIN_WORDS=100
      - SUMMARY_MAX_WORDS=150
      - LLM_ENGINE=anthropic
      - CELERY_BROKER_URL=amqps://xphtxctu:v5DL_TOb3a42b0ji4eklkhiYuCg_lOwv@kebnekaise.lmq.cloudamqp.com/xphtxctu
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - SENTRY_DSN=${SENTRY_DSN}
    entrypoint: "/entrypoint-celery-worker"
    networks:
      - rabbitmq-net


networks:
  rabbitmq-net:

volumes:
    vault-file:
    minio_data:
