"""
Django settings for alicebob project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import ssl

import decouple
import dj_database_url

from pathlib import Path

from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from pygments.lexer import default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7be4a07985cd0492d1fab2b2e3a3f54e9f88747adfd7096149143e4909d5f5e2e357f8d0778cf7bd9e20b6be9f68ef3dc982a8ac3a7201f85dac4e9f39316'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config('DEBUG', default=False, cast=bool)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'https://awesome-backstage.alicebob.io'
    'https://pro.alicebob.io'
]
ALLOWED_HOSTS = [
    '*'
]

# Application definition

INSTALLED_APPS = [
    # The order is important
    'awesome_admin',

    # Unfold
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third party apps
    'django_celery_beat',
    'simple_history',
    'import_export',
    'django_db_logger',
    'cacheops',

    # Custom apps
    'academy',
    'ezycourse',
    'news',
    'campaigns',
    'authentication',
]

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Third party middleware
    'simple_history.middleware.HistoryRequestMiddleware'

]

if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = [
        '127.0.0.1',
    ]

ROOT_URLCONF = 'alicebob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alicebob.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=decouple.config('DATABASE_URL', default='sqlite:///db.sqlite3')),
}

REDIS_URL = decouple.config('REDIS_URL', default="redis://localhost:6900/0")

# CACHES = {
#     'default': {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         'LOCATION': REDIS_URL,
#     },
# }
#
# CACHEOPS_REDIS = REDIS_URL
# CACHEOPS = {
#     'auth.*': {'ops': 'all', 'timeout': 60 * 60 * 24},
#     'academy.*': {'ops': 'all', 'timeout': 60 * 5},
#     "*.*": {'timeout': 60 * 60},
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -------------------------------------------------------------------------
# User model
# -------------------------------------------------------------------------
AUTH_USER_MODEL = 'authentication.AliceBobUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(decouple.config('STATIC_ROOT', default='/staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------------
# Webhook settings
# -------------------------------------------------------------------------
URL_TOKEN = decouple.config('URL_TOKEN', default=None)

if not DEBUG:
    # Add Sentry
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=decouple.config('SENTRY_DSN', default=None),
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        _experiments={
            "continuous_profiling_auto_start": True,
        },
    )

# -------------------------------------------------------------------------
# Celery Settings
# -------------------------------------------------------------------------
CELERY_BROKER_URL = decouple.config('CELERY_BROKER_URL', default='amqp://guest:guest@localhost')
CELERY_RESULT_BACKEND = decouple.config('CELERY_BACKEND_URL', default=None)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

if CELERY_BROKER_URL.startswith('rediss') or CELERY_BROKER_URL.startswith('amqps'):
    CELERY_BROKER_USE_SSL = {
        'cert_reqs': ssl.CERT_NONE,  # Disable SSL certificate verification
        'ssl_version': ssl.PROTOCOL_TLS,
    }

# -------------------------------------------------------------------------
# EzyCourse Settings
# -------------------------------------------------------------------------
EZYCOURSE_ADMIN_EMAIL = decouple.config('EZYCOURSE_ADMIN_EMAIL', default="cr0hn@cr0hn.com")
EZYCOURSE_BOB_EMAIL = decouple.config('EZYCOURSE_BOB_EMAIL', default="bob@alicebob.io")
EZYCOURSE_ALICE_EMAIL = decouple.config('EZYCOURSE_ALICE_EMAIL', default="alice@alicebob.io")

# -------------------------------------------------------------------------
# Zoho Settings
# -------------------------------------------------------------------------

# When this is set to True, the system will sync to the Zoho CRM. Otherwise, only local data will be used.
ZOHO_ENABLE_SYNC = decouple.config('ZOHO_ENABLE_SYNC', default=False, cast=bool)

# -------------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'db': {
            'handlers': ['db_log'],
            'level': 'DEBUG'
        },
        'django.request': {  # logging 500 errors to database
            'handlers': ['db_log'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}

# -------------------------------------------------------------------------
# Unfold settings: settings el tema de Django Admin: https://unfoldadmin.com/
# -------------------------------------------------------------------------

# LOS ICONOS SE PUEDEN ENCONTRAR EN: https://fonts.google.com/icons
UNFOLD = {
    "SITE_TITLE": "Alice & Bob - Backstage",
    "SITE_HEADER": "Alice & Bob - Backstage",
    "ENVIRONMENT": "awesome_admin.unfold_callbacks.environment_callback",
    "SITE_LOGO": {
        "light": lambda request: static('awesome_admin/logo-512x512.png'),
        "dark": lambda request: static('awesome_admin/logo-512x512.png'),
    },
    "DASHBOARD_CALLBACK": "awesome_admin.unfold_callbacks.dashboard_callback",
    "TABS": [
        {
            "models": [
                "academy.student",
                "academy.StudentContactProxy"
                "academy.StudentLeadProxy",
            ],
            "items": [
                {
                    # Todos los estudiantes
                    "title": _("Estudiantes"),
                    "link": reverse_lazy("admin:admin-student-all"),
                },
                {
                    # Leads solo
                    "title": _("Leads"),
                    "link": reverse_lazy("admin:admin-student-leads"),
                },
                {
                    # de pago
                    "title": _("Estudiantes que han comprado"),
                    "link": reverse_lazy("admin:admin-student-paid"),
                }
            ]
        }
    ],
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": _("Academia"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Estudiantes"),
                        "link": reverse_lazy("admin:academy_student_changelist"),
                        "icon": "people",
                    },
                    {
                        "title": _("Cursos"),
                        "link": lambda request: f"{reverse_lazy("admin:academy_product_changelist")}?product_type__exact=COURSE",
                        "icon": "school",
                    },
                    {
                        "title": _("Comunidades"),
                        "link": lambda request: f"{reverse_lazy("admin:academy_product_changelist")}?product_type__exact=COMMUNITY",
                        "icon": "communities",
                    },
                    {
                        "title": _("Ventas"),
                        "link": lambda request: f"{reverse_lazy("admin:academy_sells_changelist")}?sell_price__gt=0",
                        "icon": "shopping_cart",
                    },
                    {
                        "title": _("Tags"),
                        "link": reverse_lazy("admin:academy_tag_changelist"),
                        "icon": "label",
                    },
                ]
            },

            {
                # Marketing
                "title": _("Marketing"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Campañas"),
                        "link": reverse_lazy("admin:campaigns_dailyemail_changelist"),
                        "icon": "email",
                    },
                    {
                        # listas
                        "title": _("Listas"),
                        "link": reverse_lazy("admin:campaigns_maillist_changelist"),
                        "icon": "list",
                    }
                ]
            },

            {
                # Marketing
                "title": _("Copywriting"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        # listas
                        "title": _("Listas"),
                        "link": reverse_lazy("admin:campaigns_maillist_changelist"),
                        "icon": "list",
                    },
                    {
                        # news
                        "title": _("Tags"),
                        "link": reverse_lazy("admin:news_newstag_changelist"),
                        "icon": "label",
                    }
                ]
            },

            # Admin de django: Grupos y usuarios
            {
                "title": _("Administración"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Logs"),
                        "link": reverse_lazy("admin:django_db_logger_statuslog_changelist"),
                        "icon": "password",
                    },
                    {
                        "title": _("Usuarios"),
                        "link": reverse_lazy("admin:authentication_alicebobuser_changelist"),
                        "icon": "people",
                    },
                    {
                        "title": _("Grupos"),
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "icon": "communities",
                    },
                ]
            }
        ]
    },
}


# -------------------------------------------------------------------------
# Acumbamail
# -------------------------------------------------------------------------
ACUMBAMAIL_TOKEN = decouple.config('ACUMBAMAIL_TOKEN', default=None)

ACUMBAMAIL_MAIL_LIST_ALL_USERS = "alicebob-all-users"
ACUMBAMAIL_MAIL_LIST_CONTACTS = "alicebob-contacts"
ACUMBAMAIL_MAIL_LIST_LEADS = "alicebob-leads"
ACUMBAMAIL_SENDER_COUNTRY = "Estonia"
ACUMBAMAIL_SENDER_COMPANY = "Zylentech OÜ"
ACUMBAMAIL_SENDER_EMAIL = "hello@alicebob.io"
ACUMBAMAIL_SENDER_NAME = "Alice"
