# Generated by Django 5.1.3 on 2024-11-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohooauth',
            name='expiry_time',
            field=models.BigIntegerField(),
        ),
    ]
