# Generated by Django 5.1.3 on 2024-11-21 09:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0002_alter_zohooauth_expiry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalZohoOAuth',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=255)),
                ('client_secret', models.CharField(db_index=True, max_length=255)),
                ('grant_token', models.CharField(db_index=True, max_length=255)),
                ('refresh_token', models.CharField(db_index=True, max_length=255)),
                ('access_token', models.CharField(db_index=True, max_length=255)),
                ('expiry_time', models.BigIntegerField()),
                ('api_domain', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Zoho OAuth',
                'verbose_name_plural': 'historical Zoho OAuth',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
