# Generated by Django 5.1.3 on 2024-11-26 09:26

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_courseprogress_zoho_id_and_more'),
        ('zoho', '0004_historicalzohocontact_historicalzohocourseprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalzohocontact',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzohocourseprogress',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzoholead',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzohoproduct',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalzohopurchaseorders',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zohocontact',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zohocourseprogress',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zoholead',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zohoproduct',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zohopurchaseorders',
            name='zoho_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='zohocourseprogress',
            unique_together={('student', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='zohopurchaseorders',
            unique_together={('student', 'product')},
        ),
        migrations.CreateModel(
            name='HistoricalZohoTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('zoho_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academy.tag')),
            ],
            options={
                'verbose_name': 'historical Zoho Tag',
                'verbose_name_plural': 'historical Zoho Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ZohoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('zoho_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.tag')),
            ],
            options={
                'verbose_name': 'Zoho Tag',
                'verbose_name_plural': 'Zoho Tags',
                'db_table': 'zoho_tags',
            },
        ),
    ]
