# Generated by Django 5.1.3 on 2024-11-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_courseprogress_zoho_id_and_more'),
        ('zoho', '0005_alter_historicalzohocontact_zoho_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zohopurchaseorders',
            name='zoho_purcha_student_9dadd9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='zohopurchaseorders',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalzohopurchaseorders',
            name='sell',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academy.sells'),
        ),
        migrations.AddField(
            model_name='zohopurchaseorders',
            name='sell',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.sells'),
        ),
        migrations.AlterUniqueTogether(
            name='zohopurchaseorders',
            unique_together={('student', 'product', 'sell')},
        ),
        migrations.AddIndex(
            model_name='zohopurchaseorders',
            index=models.Index(fields=['student', 'product', 'sell'], name='zoho_purcha_student_46451d_idx'),
        ),
    ]
