# Generated by Django 5.1.3 on 2024-11-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_courseprogress_zoho_id_and_more'),
        ('zoho', '0006_remove_zohopurchaseorders_zoho_purcha_student_9dadd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zohocourseprogress',
            unique_together={('student', 'product', 'course_progress')},
        ),
    ]
