# Generated by Django 5.1.3 on 2024-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0007_alter_zohocourseprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohocontact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts_tags', to='zoho.zohotag'),
        ),
        migrations.AddField(
            model_name='zoholead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads_tags', to='zoho.zohotag'),
        ),
        migrations.AddField(
            model_name='zohoproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products_tags', to='zoho.zohotag'),
        ),
    ]
