# Generated by Django 5.1.3 on 2024-11-26 14:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Origin',
                'verbose_name_plural': 'Origins',
                'db_table': 'news_origins',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags_news',
            },
        ),
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='news.newsprovider')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'news_channels',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('linkedin', models.TextField(help_text='Text for LinkedIn')),
                ('twitter', models.TextField(help_text='Text for Twitter')),
                ('url', models.URLField(blank=True, help_text='URL to the news', null=True)),
                ('image', models.URLField(blank=True, help_text='URL to the image', null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('BACKLOG', 'BACKLOG'), ('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED'), ('REVIEW', 'REVIEW')], default=news.models.NewsState['BACKLOG'], max_length=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newschannel')),
                ('tags', models.ManyToManyField(blank=True, to='news.newstag')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['created'],
            },
        ),
    ]
