# Generated by Django 5.1.3 on 2024-11-26 15:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsprovider_options_alter_newsprovider_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzycourseChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EzyCourse Channel',
                'verbose_name_plural': 'EzyCourse Channels',
                'db_table': 'ezycourse_channels',
            },
        ),
        migrations.CreateModel(
            name='EzyCourseCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ezy_id', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EzyCourse Community',
                'verbose_name_plural': 'EzyCourse Communities',
                'db_table': 'ezy_course_communities',
            },
        ),
        migrations.RenameField(
            model_name='news',
            old_name='channel',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='news',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='news',
            name='twitter',
        ),
        migrations.AddField(
            model_name='news',
            name='ezycourse_text',
            field=models.TextField(blank=True, help_text='Text for EzyCourse community', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='linkedin_text',
            field=models.TextField(blank=True, help_text='Text for LinkedIn', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='twitter_text',
            field=models.TextField(blank=True, help_text='Text for Twitter', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='The full content of the news'),
        ),
        migrations.AddField(
            model_name='news',
            name='ezycourse_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.ezycoursechannel'),
        ),
        migrations.AddField(
            model_name='ezycoursechannel',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='news.ezycoursecommunity'),
        ),
    ]
