# Generated by Django 5.1.3 on 2024-11-28 14:05

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news', '0003_ezycoursechannel_ezycoursecommunity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzycoursePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('channel', models.CharField(choices=[('GENERAL', 'GENERAL'), ('EVENTOS', 'EVENTOS'), ('API_REST', 'API_REST'), ('IA', 'IA'), ('NOTICIAS', 'NOTICIAS'), ('TOP_CVES', 'TOP_CVES')], default=news.models.EzycourseChannels['GENERAL'], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ezycoursechannel',
            name='community',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ezycourse_channel',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ezycourse_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='linkedin_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='twitter_text',
        ),
        migrations.AddField(
            model_name='news',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ChannelPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to='news.news')),
            ],
        ),
        migrations.DeleteModel(
            name='EzyCourseCommunity',
        ),
        migrations.DeleteModel(
            name='EzycourseChannel',
        ),
    ]
