# Generated by Django 5.1.3 on 2024-11-28 14:41

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_ezycoursepublication_linkedinpublication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpublication',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='channelpublication',
            name='news',
        ),
        migrations.DeleteModel(
            name='EzycoursePublication',
        ),
        migrations.DeleteModel(
            name='LinkedInPublication',
        ),
        migrations.DeleteModel(
            name='TelegramPublication',
        ),
        migrations.DeleteModel(
            name='TwitterPublication',
        ),
        migrations.AddField(
            model_name='news',
            name='ezy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ezycourse_channel',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('EVENTOS', 'EVENTOS'), ('API_REST', 'API_REST'), ('IA', 'IA'), ('NOTICIAS', 'NOTICIAS'), ('TOP_CVES', 'TOP_CVES')], default=news.models.EzycourseChannels['GENERAL'], max_length=40),
        ),
        migrations.AddField(
            model_name='news',
            name='linkedin_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='telegram_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='twitter_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChannelPublication',
        ),
    ]
