# Generated by Django 5.1.3 on 2024-12-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstag',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='color',
            field=models.CharField(default='blue', max_length=40),
        ),
    ]
