# Generated by Django 5.1.3 on 2024-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EzyCourseAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('session_cookie', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'EzyCourse Auth',
                'verbose_name_plural': 'EzyCourse Auth',
                'db_table': 'ezycourse_auth',
                'indexes': [models.Index(fields=['access_token', 'session_cookie'], name='ezycourse_a_access__8b5149_idx')],
            },
        ),
    ]
