# Generated by Django 5.1.3 on 2024-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezycourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezycourseauth',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ezycourseauth',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
