# Generated by Django 5.1.3 on 2024-11-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezycourse', '0002_ezycourseauth_email_ezycourseauth_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ezycourseauth',
            name='ezycourse_a_access__8b5149_idx',
        ),
        migrations.RemoveField(
            model_name='ezycourseauth',
            name='access_token',
        ),
    ]
